services:
  backend:
    build: ./pathpilot-backend
    ports:
      - "5001:5000"
    env_file:
      - ./pathpilot-backend/.env
    volumes:
      - ./pathpilot-backend:/app
  frontend:
    build: ./pathpilot-frontend
    ports:
      - "5003:5000"
    depends_on:
      - backend
    volumes:
      - ./pathpilot-frontend:/app
  monitoring:
    build: ./pathpilot-monitoring
    ports:
      - "5005:8050"
    depends_on:
      - backend
    volumes:
      - ./pathpilot-monitoring:/dashboard